### ISSUE TITLE
Bug Websocket on Chrome

### ISSUE THREAD

**Issue by samuelfaberdev** [GorskiAnthony/retro-wcs#6]
Le Websocket me fait une erreur 404 sur Chrome
Ca n'affiche plus les nouvelles cards non plus.

Sur Firefox les nouvelles cards fonctionnent bien et pas de 404 sur le Websocket

**Comment by GorskiAnthony** [comment]
Navigateur : 

- [ ] Google Chrome
- [ ] Firefox
- [ ] Edge
